version: '3'

services:
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - DOT_START=off
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES="United States"
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HEALTH_VPN_DURATION_INITIAL=600s
      - HEALTH_VPN_DURATION_ADDITION=600s
      - HEALTH_SUCCESS_WAIT_DURATION=600s
      - LOG_LEVEL=debug
    ports:
      - 11470:11470
      - 12470:12470
    restart: unless-stopped

  streamio:
    image: stremio/server:latest
    container_name: streamio
    network_mode: service:vpn
    depends_on:
      - vpn
    restart: unless-stopped
